postgresdb:
  host: localhost:5445
  user: "gows"
  password: "gows"
  dbname: "gowsdb"
  sslmode: "disable"


server:
  port: "0.0.0.0:9090"


paseto:
  symmetrickey: "fady123456789gamil123456789mahro"
  access_token_expiration: 15m
  refresh_token_expiration: 24h